name: DotNet app deploy to EKS
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0' # default is latest stable
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{secrets.AWS_REGION}}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}

      run: |
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/dotnetsql-api:latest-${{ github.sha }} -f Dockerfile_Api .
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/dotnetsql-worker:latest-${{ github.sha }} -f Dockerfile_Worker .

        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/dotnetsql-api:latest-${{ github.sha }}
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/dotnetsql-worker:latest-${{ github.sha }}
    - name: Extract Docker image tag
      id: extract-tag
      run: echo "::set-output name=tag::${{ github.sha }}"
    - name: Update deployment.yaml
      run: |
        ls
        cd Manifests
        sed  -i '/dotnetsql-api/ s/:latest-.*$/:latest-${{ steps.extract-tag.outputs.tag }}/' deployment-api.yaml
        sed  -i '/dotnetsql-worker/ s/:latest-.*$/:latest-${{ steps.extract-tag.outputs.tag }}/' deployment-worker.yaml
        echo "reading file"
        cat deployment-api.yaml
        git config --global user.email "dev@demo.com"
        git config --global user.name "demodev"
        git status
        git add . 
        git commit -m "Update to new version"
        git push
    - name: Update kube config
      run: aws eks update-kubeconfig --name hackathon-eks
    - name: Deploy to EKS
      run: |
        cd Manifests
        kubectl apply -f deployment-api.yaml -n dotnetsql-ns
        kubectl apply -f service-api.yaml -n dotnetsql-ns
        kubectl apply -f deployment-worker.yaml -n dotnetsql-ns
        kubectl apply -f service-worker.yaml -n dotnetsql-ns
